language: java
jdk:
  - openjdk21

branches:
  only:
    - dev

before_install:
  - chmod +x gradlew

script:
  - ./gradlew test

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - doyelbenitez@gmail.com
    on_success: never
    on_failure: always
