# application-dev.properties

# Configuración de MongoDB
spring:
  data:
    mongodb:
      host: ${MDB_HOST}
      port: ${MDB_PORT}
      database: ${MDB_NAME}
      username: ${MDB_USERNAME}
      password: ${MDB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#Configuracion de TokenJWT
security:
  jwt:
    secret-key-path-prod: '../webapps/tesis/WEB-INF/classes/jwtSecret.key'