# application-dev.yaml
spring:
  security:
    user:
      name: ${API_USER}
      password: ${API_PASSWORD}

  # Configuracion de PostgreSQL
  datasource:
    url: jdbc:postgresql://${PDB_HOST}:${PDB_PORT}/${PDB_NAME}
    username: ${PDB_USERNAME}
    password: ${PDB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Configuración de MongoDB
  data:
    mongodb:
      host: ${MDB_HOST}
      port: ${MDB_PORT}
      database: ${MDB_NAME}
      username: ${MDB_USERNAME}
      password: ${MDB_PASSWORD}

# Configuracion de JWT
security:
  jwt:
    secret-key-path: 'jwtSecret.key'