# application.yaml
server:
  servlet:
    context-path: '/challenge/api/'

spring:
  application:
    name: 'challenge'

security:
  jwt:
    token:
      expire-in-milliseconds: 3600000
    key-dynamic: ${KEY_DYNAMIC}

# Log Configuration
logging:
  level:
    org:
      springframework:
        # web: 'DEBUG'
        web.filter.CommonsRequestLoggingFilter: 'DEBUG'
        # hibernate: 'DEBUG'
      SQL: 'DEBUG'
      apache:
        coyote:
          http11: 'DEBUG'
      # type: 'TRACE'
      tool:
      # schema: 'TRACE'