name: Update Deployment Status Badge

on:
  schedule:
    - cron: '*/2 * * * *'  
  workflow_dispatch:       # Permite ejecución manual

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest deployment status from GitHub (master branch)
        id: deployment-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Obtener el estado del último despliegue en la rama master
          STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/deployments?ref=refs/heads/master" \
            | jq -r '.[0].statuses_url' | xargs -I {} curl -s -H "Authorization: token $GITHUB_TOKEN" {} \
            | jq -r '.[0].state')

          echo "Deployment Status: $STATUS"
          echo "::set-output name=status::$STATUS"

      - name: Update README with deployment badge
        run: |
          STATUS=${{ steps.deployment-status.outputs.status }}
          if [[ "$STATUS" == "active" ]]; then
            COLOR="brightgreen"
          elif [[ "$STATUS" == "in_progress" ]]; then
            COLOR="yellow"
          else
            COLOR="red"
          fi
          BADGE_URL="https://img.shields.io/badge/deployment-$STATUS-$COLOR"
          sed -i 's|!\[Deployment Status\](.*)|![Deployment Status]('"$BADGE_URL"')|' README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Update deployment status badge"
          git push
